### ISSUE TITLE
Shapely import issue on Darwin

### ISSUE THREAD

**Issue by aaraney** [cheginit/hydrodata#28]
* Hydrodata version: 0.4.4
* Python version: 3.7.7
* Operating System: macOS 10.14.4
- [x] Using Conda

### Description

I found an issue when importing any `from shapely.geometry` packages on Shapely 1.7.0.
Getting the following:

``` bash
File "/Users/austinraney/miniconda3/envs/hydrodata/lib/python3.7/site-packages/shapely/geos.py", line 62, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib cxx or load any of its variants [].
```

I found the related [issue](https://github.com/Toblerity/Shapely/issues/888) and it seems that the [PR](https://github.com/Toblerity/Shapely/pull/891) fixed it (I tested the change on my system at least). Just something to know about. Hopefully they will update the package on PyPI soon.

### What I Did

``` bash
python -c "from shapely.geometry import Point"
```

**Comment by cheginit** [comment]
Thanks for reporting it. I think that at some point Mac can also be added to the CI as well.

**Comment by aaraney** [comment]
For sure. Yeah I agree. Ill mess with that real quick and see if I can get a PR to work on both Linux and Mac since master doesn't include shapely at the moment. I also noticed that the `secure` in the yaml file is not being passed from Travis.

**Comment by cheginit** [comment]
Thanks, that would cool!
I am planning to migrate to Github Actions from Travis. I used [xarray](https://github.com/pydata/xarray)  for setting up many of the config files and it seems that Github Actions is the direction that they're moving. For example, you can see [xarray-simlab](https://github.com/benbovy/xarray-simlab/actions).

**Comment by aaraney** [comment]
Well, sorry for being away and not so communicative, I was busy wrangling travis lol. Thats insane, thanks for the simlab share but good god thats a ton of yaml. Are there travis yaml automators?

**Comment by cheginit** [comment]
Yes, there are a lot of config files. I used the [cookie cutter](https://github.com/audreyr/cookiecutter-pypackage) project to get the project set up properly and then used xarray's config to set up linters. It takes a while to set up everything but results in an automated workflow that just works and you don't have to worry about formatting and testing.

**Comment by cheginit** [comment]
It seems that the problem is solved. Thanks for reporting.
